POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "create blog using node",
	"author": "arjun",
	"url": "mongo and express",
	"likes": 99
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "create blog using node",
	"author": "arjun",
	"url": "mongo and express",
	"likes": 99,
	"userId": "658abba32087403478c8ad22"
}

###
PUT http://localhost:3001/api/blogs/65817b5e524feaed1de07c7e
Content-Type: application/json

{
	"author": "arjun"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "ar",
	"name": "Arjun Sah",
	"password": ""
}