POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "create blog using node",
	"author": "arjun",
	"url": "mongo and express",
	"likes": 99
}

###
PUT http://localhost:3001/api/blogs/65817b5e524feaed1de07c7e
Content-Type: application/json

{
	"author": "arjun"
}